project:
  type: website

lang: en

execute:
  freeze: auto  # re-render only when source changes
  echo: false
  warning: false
  message: false

website:
  title: "Mobio Report"
  navbar:
    background: primary
    right:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: flatly
    toc: true
    tbl-cap-location: top
    fig-cap-location: top